#!/bin/bash

WALL_DIR="$HOME/Pictures/wallpapers"
CACHE_DIR="$HOME/.cache/wall_thumbs"
COLORS_CSS="$HOME/dotfiles/waybar/colors/colors.css"
mkdir -p "$CACHE_DIR"

# Helper — send notification via swaync
notify() {
    notify-send -a "Wallpaper Switcher" "$1" "$2"
    swaync-client -sw &>/dev/null
}

# Start swww daemon if not running
if ! pgrep -x swww-daemon > /dev/null; then
    swww-daemon --no-cache &
fi

# Collect images
shopt -s nullglob nocaseglob
IMAGES=("$WALL_DIR"/*.{jpg,jpeg,png,webp,gif})
shopt -u nullglob nocaseglob

if [ ${#IMAGES[@]} -eq 0 ]; then
    notify "No images found" "$WALL_DIR"
    exit 1
fi

# Generate thumbnails in parallel (skips cached ones)
for img in "${IMAGES[@]}"; do
    name=$(basename "$img")
    thumb="$CACHE_DIR/${name%.*}.png"
    [ ! -f "$thumb" ] && magick "$img" -resize 300x200^ -gravity Center -extent 300x200 "$thumb" 2>/dev/null &
done
wait

# Build rofi menu
MENU=""
FILENAMES=()
for img in "${IMAGES[@]}"; do
    name=$(basename "$img")
    thumb="$CACHE_DIR/${name%.*}.png"
    if [ -f "$thumb" ]; then
        MENU+="${name}\x00icon\x1f${thumb}\n"
        FILENAMES+=("$img")
    fi
done

if [ -z "$MENU" ]; then
    notify "Error" "Thumbnails failed. Is imagemagick installed?"
    exit 1
fi

# Show rofi picker
CHOICE_INDEX=$(printf "%b" "$MENU" | rofi \
    -dmenu \
    -show-icons \
    -theme "$HOME/dotfiles/rofi/wallpaper.rasi" \
    -format i)

[ -z "$CHOICE_INDEX" ] && exit 0

FULL_PATH="${FILENAMES[$CHOICE_INDEX]}"

if [ -z "$FULL_PATH" ] || [ ! -f "$FULL_PATH" ]; then
    notify "Error" "Could not resolve selection (index: $CHOICE_INDEX)"
    exit 1
fi

# ── 1. Apply wallpaper immediately ────────────────────────────────────────
awww img "$FULL_PATH" \
    --transition-type fade \
    --transition-fps 60 \
    --transition-duration 2

# ── 2. Run pywal + write colors.css + reload waybar in background ─────────
# This runs async so the script exits fast — no visible delay
(
    # Generate palette (-n = no terminal colors, -e = no wallpaper setter)
    wal -i "$FULL_PATH" -n -e -q

    WAL_CACHE="$HOME/.cache/wal/colors.sh"
    [ ! -f "$WAL_CACHE" ] && exit 1

    source "$WAL_CACHE"

    # Darken/lighten helpers using python3
    darken()  { python3 -c "c='$1'.lstrip('#');r,g,b=int(c[0:2],16),int(c[2:4],16),int(c[4:6],16);f=$2;print('#{:02x}{:02x}{:02x}'.format(int(r*f),int(g*f),int(b*f)))"; }
    lighten() { python3 -c "c='$1'.lstrip('#');r,g,b=int(c[0:2],16),int(c[2:4],16),int(c[4:6],16);f=$2;print('#{:02x}{:02x}{:02x}'.format(min(255,int(r*f)),min(255,int(g*f)),min(255,int(b*f))))"; }

    BG0=$(darken  "$background" 0.85)
    BG1="$background"
    BG2=$(lighten "$background" 1.3)
    BG3=$(lighten "$background" 1.6)
    BG4=$(lighten "$background" 1.9)
    FG="$foreground"
    RED="$color1"
    ORANGE="$color3"
    YELLOW="$color3"
    GREEN="$color2"
    AQUA="$color6"
    BLUE="$color4"
    PURPLE="$color5"
    GREY0=$(darken "$foreground" 0.75)
    GREY1=$(darken "$foreground" 0.60)
    GREY2=$(darken "$foreground" 0.50)

    mkdir -p "$(dirname "$COLORS_CSS")"
    cat > "$COLORS_CSS" << CSSEOF
/* Auto-generated — do not edit manually */
/* Wallpaper: $(basename "$FULL_PATH") */

@define-color bg0 ${BG0};
@define-color bg1 ${BG1};
@define-color bg2 ${BG2};
@define-color bg3 ${BG3};
@define-color bg4 ${BG4};
@define-color fg ${FG};
@define-color red ${RED};
@define-color orange ${ORANGE};
@define-color yellow ${YELLOW};
@define-color green ${GREEN};
@define-color aqua ${AQUA};
@define-color blue ${BLUE};
@define-color purple ${PURPLE};
@define-color grey0 ${GREY0};
@define-color grey1 ${GREY1};
@define-color grey2 ${GREY2};
CSSEOF

    # Generate rofi colors file from pywal palette
    cat > "$HOME/.cache/wal/colors-rofi-dark.rasi" << RASIEOF
/* pywal — generated by rofi_wall.sh */
* {
    background:     ${color0};
    background-alt: ${color8};
    foreground:     ${foreground};
    color1:         ${color1};
    color2:         ${color2};
    color3:         ${color3};
    color4:         ${color4};
    color5:         ${color5};
    color6:         ${color6};
}
RASIEOF

    # Reload waybar after colors are written
    if pgrep -x waybar > /dev/null; then
        pkill -SIGUSR2 waybar 2>/dev/null \
            || { pkill waybar; sleep 0.3; waybar & disown; }
    else
        waybar & disown
    fi

    # notify "Colors updated" "$(basename "$FULL_PATH")"
) & disown

# ── 3. Notify wallpaper set immediately (don't wait for colors) ───────────
# notify "Wallpaper set" "$(basename "$FULL_PATH")"
echo "Set wallpaper: $FULL_PATH"
